import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
<<<<<<< Updated upstream
  title: "Maalomatiia",
  description: "Generated by create next app",
=======
  title: "Maaloomatiia",
  description:
    "Data & AI capability partner enabling enterprise teams across MENA to move from technology adoption to real delivery.",
>>>>>>> Stashed changes
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${montserrat.variable} h-full antialiased`}>
      <body className="min-h-full flex flex-col bg-brand-dark-navy text-white">
        {children}
      </body>
    </html>
  );
}
